
#    ## Every Database needs the schema to be loaded for the application to work.
#
#    Download the schema and load it.
#
#    ```
#    # curl -s -L -o /tmp/mongodb.zip "https://github.com/roboshop-devops-project/mongodb/archive/main.zip"
#
#    # cd /tmp
#    # unzip mongodb.zip
#    # cd mongodb-main
#    # mongo < catalogue.js
#    # mongo < users.js
#
#    ```
- name: Copy MongoDB Repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install the Mongodb
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: Update MongoDB listen address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start MongoDB Service
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    enabled: yes

- name: Download database code
  import_role:
    name: common
    tasks_from: download

- name: Load Schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/catalogue.js"
    idempotent: yes

- name: Load Schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/users.js"
    idempotent: yes