- name: Copy Mysql Repo
  ansible.builtin.copy:
    name: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install Mysql
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed

- name: Start Mysql Service
  ansible.builtin.systemd:
    name: mysqld
    state: restarted
    enabled: yes
