- name: Copy Mysql Repo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install Mysql
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed

- name: Start Mysql Service
  ansible.builtin.systemd:
    name: mysqld
    state: restarted
    enabled: yes

- name: Check if new password is working
  mysql_info:
    login_user: root
    login_password: RoboShop@1
    filter: databases

- name: Install PyMySQL
  ansible.builtin.yum:
    name: PyMySQL
    state: installed

- name: Find the temporary Password
  ansible.builtin.shell: grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}'
  register: mysql_output

- name: Print
  ansible.builtin.debug:
    msg: "{{mysql_output}}"